services:
  - docker

cache: docker

branches:
  only:
    - master
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

matrix:
  include:
    - env: ARCH=x86_64

script:
  - docker run --cap-add SYS_ADMIN --device /dev/fuse --mount src=$PWD,dst=/work,type=bind niess/linuxdeploy-plugin-python:${ARCH} ./build-python.sh

after_success:
  - ls -lha *.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.AppImage
